- user:
    name: Sergio
    email: sdelquin@gmail.com
  products:
    - alias: Sierra de mesa
      url: https://www.amazon.es/DeWalt-DWE7485-QS-DWE7485-QS-Sierra-1-850W-%C3%98210mm-Mesa-610x305mm-Port%C3%A1til/dp/B07YYTDK1D/
    - alias: Mesa de corte
      url: https://www.amazon.es/MTL-79286-Vade-corte-PVC/dp/B01J1N3J8Q/
